### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1e+05'

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [stjude/ROSE#17]
Hello,
I had this error after running a long time on 16 core cpu, 384gb ram and python 3.6. How can I solve this? ROSE version is 1.3.1

```
Warning message:
In write.table(file = outputFile, superEnhancer, sep = "\t", quote = FALSE,  :
  appending column names to file
Warning message:
In write.table(file = outputFile, superEnhancer, sep = "\t", quote = FALSE,  :
  appending column names to file
Traceback (most recent call last):
  File "/cm/shared/apps/ROSE/bin/ROSE_geneMapper.py", line 291, in <module>
    main()
  File "/cm/shared/apps/ROSE/bin/ROSE_geneMapper.py", line 277, in main
    enhancerToGeneTable,geneToEnhancerTable = mapEnhancerToGene(annotFile,enhancerFile,uniqueGenes=True,byRefseq=options.refseq, transcribedFile=transcribedFile)
  File "/cm/shared/apps/ROSE/bin/ROSE_geneMapper.py", line 192, in mapEnhancerToGene
    enhancerOrder = ROSE_utils.order([int(line[-2]) for line in enhancerToGeneTable[1:]])
  File "/cm/shared/apps/ROSE/bin/ROSE_geneMapper.py", line 192, in <listcomp>
    enhancerOrder = ROSE_utils.order([int(line[-2]) for line in enhancerToGeneTable[1:]])
ValueError: invalid literal for int() with base 10: '1e+05'
```

**Comment by madetunj** [comment]
can you share the syntax used to generate this error?

**Comment by alirizaaribas-ibg** [comment]
Hello @madetunj,
We use job scheduler Slurm. Here is the slurm file for this job:

```
#!/bin/bash
#SBATCH -p ulimited3
#SBATCH -J rose_1
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=username@ibg.edu.tr
#SBATCH --output=rose1-output-%j.out
#SBATCH --error=rose1-error-%j.err

PATHTO=/cm/shared/apps/ROSE
PYTHONPATH=$PATHTO/lib
alias python=python3
export PYTHONPATH
export PATH=$PATH:$PATHTO/bin
module load samtools/1.9.0 

ROSE_main.py -g MM10 -i /archive/username/Vehicle_broad/Vehicle_K27Ac_IP-S1_R1_broad_peaks.gff -r /archive/username/Vehicle_broad/Vehicle_K27Ac_IP-S1_R1.mLb.clN.sorted.bam -c /archive/username/PT48_broad_pooled/pooled_input_R1.mLb.clN.sorted.bam -o /archive/username/Vehicle_broad/output_2/
```

The path of ROSE is `/cm/shared/apps/ROSE/bin/`.

The output file is:
[rose1-output-10713.out.txt](https://github.com/stjude/ROSE/files/8560568/rose1-output-10713.out.txt)

The error file is:
[rose1-error-10713.err.txt](https://github.com/stjude/ROSE/files/8560569/rose1-error-10713.err.txt)
