### ISSUE TITLE
UnboundLocalError: local variable 'startDict' referenced before assignment

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [stjude/ROSE#22]
Hi, 
First of all, Thank you guys very much for developing this useful tool. I am trying using ROSE through custome genome annotation which is download from UCSC and formated in ncbiRefSeq style. However when I try `--custom=` parameter, it keeps throwing the following error.
```shell
USING ./Monkey_H3K4me_SE/gff/H3K4me.macs2_peaks.narrowPeak.gff AS THE INPUT GFF
USING CUSTOM GENOME Mmul10 AS THE GENOME FILE
MAKING START DICT
Traceback (most recent call last):
  File "/gpfs/home/zhangyue/biosoft/ROSE-master/bin/ROSE_main.py", line 496, in <module>
    main()
  File "/gpfs/home/zhangyue/biosoft/ROSE-master/bin/ROSE_main.py", line 332, in main
    startDict = ROSE_utils.makeStartDict(annotFile)
  File "/gpfs/home/zhangyue/biosoft/ROSE-master/lib/ROSE_utils.py", line 152, in makeStartDict
    return startDict
UnboundLocalError: local variable 'startDict' referenced before assignment
```
The `-g` parameter goes well.
By the way, Here I paste my code executed

```shell
python /gpfs/home/zhangyue/biosoft/ROSE-master/bin/ROSE_main.py --custom=Mmul10 \
 -i Monkey_chondrocyteH3K4me_Mmul10.gff \
 -r RM15369-H3K4me-lib2_Mmul_10.bwt2pairs_sort.bam  \
 -b RM15369-H3K4me_Mmul_10.bwt2pairs_sort.bam \
 -t 2500 -o ./Monkey_H3K4me_SE 1>SE_calling.log 2>&1
```

**Comment by madetunj** [comment]
`--custom` requires the UCSC gene annotation file. It looks like you only included the genome name.

**Comment by Gemma-Zhang-326** [comment]
Hi, Really thankful for your quick reply. Did you mean `--custom=annotation/Mmul10_refseq.ucsc` ?

**Comment by madetunj** [comment]
yes `--custom=/path/to/Mmul10_refseq.ucsc`

**Comment by Gemma-Zhang-326** [comment]
Silly me! Sorry to bother you.
