### ISSUE TITLE
Error in mapBamToGFF -- TypeError: float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by parkerstevenson** [stjude/ROSE#37]
Hello, I'm trying to run ROSE on the example ROSE_DATA provided on [http://younglab.wi.mit.edu/super_enhancer_code.html](url), but I'm running into the following errors. I checked that the bam file I downloaded is not corrupted by running  
> samtools quickcheck /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam

Any insight is appreciated!

```
python3 ROSE_main.py -g HG18 -i /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/HG18_MM1S_MED1.gff -r /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam -o /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output

USING /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/HG18_MM1S_MED1.gff AS THE INPUT GFF
USING HG18 AS THE GENOME
MAKING START DICT
LOADING IN GFF REGIONS
STITCHING REGIONS TOGETHER
PERFORMING REGION STITCHING
MAKING GFF FROM STITCHED COLLECTION
WRITING STITCHED GFF TO DISK AS /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/gff/HG18_MM1S_MED1_12.5KB_STITCHED.gff
OUTPUT WILL BE WRITTEN TO  /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/HG18_MM1S_MED1_12.5KB_STITCHED_REGION_MAP.txt
ROSE_bamToGFF.py -f 1 -e 200 -r -m 1 -b /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam -i /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/gff/HG18_MM1S_MED1_12.5KB_STITCHED.gff -o /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/mappedGFF/HG18_MM1S_MED1_12.5KB_STITCHED_MM1S_MED1.hg18.bwt.sorted.bam_MAPPED.gff &
ROSE_bamToGFF.py -f 1 -e 200 -r -m 1 -b /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam -i /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/HG18_MM1S_MED1.gff -o /Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/mappedGFF/HG18_MM1S_MED1_MM1S_MED1.hg18.bwt.sorted.bam_MAPPED.gff &
PAUSING TO MAP
{'bam': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam', 'input': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/gff/HG18_MM1S_MED1_12.5KB_STITCHED.gff', 'output': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/mappedGFF/HG18_MM1S_MED1_12.5KB_STITCHED_MM1S_MED1.hg18.bwt.sorted.bam_MAPPED.gff', 'sense': 'both', 'floor': '1', 'extension': '200', 'rpm': True, 'matrix': '1'}
[]
mapping to GFF and making a matrix with fixed bin number
{'bam': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/MM1S_MED1.hg18.bwt.sorted.bam', 'input': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/HG18_MM1S_MED1.gff', 'output': '/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/output/mappedGFF/HG18_MM1S_MED1_MM1S_MED1.hg18.bwt.sorted.bam_MAPPED.gff', 'sense': 'both', 'floor': '1', 'extension': '200', 'rpm': True, 'matrix': '1'}
[]
mapping to GFF and making a matrix with fixed bin number
Traceback (most recent call last):
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 253, in <module>
Traceback (most recent call last):
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 253, in <module>
    main()
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 244, in main
    main()
    newGFF = mapBamToGFF(bamFile,gffFile,options.sense,int(options.extension),options.floor,options.rpm,options.matrix)
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 244, in main
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 40, in mapBamToGFF
    MMR= round(float(bam.getTotalReads('mapped'))/1000000,4)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
    newGFF = mapBamToGFF(bamFile,gffFile,options.sense,int(options.extension),options.floor,options.rpm,options.matrix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/parkerstevenson/Desktop/wimalasena_chIP/ROSE/ROSE_bamToGFF.py", line 40, in mapBamToGFF
    MMR= round(float(bam.getTotalReads('mapped'))/1000000,4)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by SLundregan** [comment]
What was your solution to this? I am getting the same error.

**Comment by hiiiyilingzhang** [comment]
Same here! 
I suspect the input bed/gff problem, but not sure. Could you please share some insights with us? Thanks so much!

**Comment by hiiiyilingzhang** [comment]
> Same here! I suspect the input bed/gff problem, but not sure. Could you please share some insights with us? Thanks so much!

Hi guys I think I found the issue. 
The error msg indicate `MMR= round(float(bam.getTotalReads('mapped'))/1000000,4)` issue, while`bam.getTotalReads` is actually using `samtools flagstat` (https://github.com/stjude/ROSE/blob/b3c7f57f518b6c5b8e7d3371d74ba43a2ea99af4/lib/ROSE_utils.py#L582C20-L582C37)

so, make sure your environment have samtools installed!
