### ISSUE TITLE
ROSE usage for mm39 genome: index out of bounds error

### ISSUE THREAD

**Issue by Brahmandam-Gayatri** [stjude/ROSE#39]
Hello,

Thank you for ROSE for calling super-enhancers. I have a query: How can I make the refseq table for mm39 and use it for stitching the super-enhancers of my ChIP-seq data?

In addition, I am getting the following error:
```
MAKING TSS COLLECTION
12900
9000
13000
13100
13200
13400
9100
13300
9200
9000
13500
9300
9400
9100
13600
13700
9200
13800
9300
13900
9400
14000
13400
14100
13500
13600
13700
13800
13900
14000
14100
9500
9600
9700
9800
14200
14300
14400
14500
14600
14200
14300
14400
14500
14600
9500
9600
9700
9800
Traceback (most recent call last):
  File "/path/to/file/ROSE/bin/ROSE_geneMapper.py", line 299, in <module>
    main()
  File "path/to/file/ROSE/bin/ROSE_geneMapper.py", line 282, in main
    enhancerToGeneTable,geneToEnhancerTable,withGenesTable = mapEnhancerToGene(annotFile,enhancerFile, uniqueGenes=True, byRefseq=options.refseq, subtractInput=options.control, transcribedFile=transcribedFile)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/file/ROSE/bin/ROSE_geneMapper.py", line 140, in mapEnhancerToGene
    closestGene = allEnhancerGenes[distList.index(min(distList))]
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```
Command used:
```
ROSE_main.py -g MM39 -i /path/to/file/treated1.bed -r /path/to/file/treated1.sorted.bam -c /path/to/file/treated1_input.sorted.bam -o . -s 12500 -t 2500
```
I have tried to make a refseq file for mm39 genome as specified in the instructions. Hence any help in this regard is highly appreciated.

Thanks & regards,
Gayatri.

**Comment by Krithika-Bhuvan** [comment]
Any resolution to this ? I',m having the same issue for hg38. I used ucsc file for hg38 that was provided. 
```
Traceback (most recent call last):
  File "/opt/conda/envs/rose/ROSE-1.3.1/bin/ROSE_main.py", line 496, in <module>
    main()
  File "/opt/conda/envs/rose/ROSE-1.3.1/bin/ROSE_main.py", line 337, in main
    referenceCollection = ROSE_utils.gffToLocusCollection(inputGFFFile)
  File "/opt/conda/envs/rose/ROSE-1.3.1/lib/ROSE_utils.py", line 473, in gffToLocusCollection
    gff = parseTable(gff,'\t')
  File "/opt/conda/envs/rose/ROSE-1.3.1/lib/ROSE_utils.py", line 50, in parseTable
    if lines[0].count('\r') > 0:
IndexError: list index out of range
```
